* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
PLUM AT_17_Sunscreen BY AT_1_Female AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=CELLINFO FIT PARAMETER SUMMARY TPARALLEL
  /SAVE=ESTPROB.

MEANS TABLES=EST1_1 EST2_1 EST3_1 EST4_1 EST5_1 BY AT_18_Skin_Color AT_1_Female
  /CELLS=MEAN COUNT STDDEV.

PLUM AT_17_Sunscreen BY AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=CELLINFO FIT PARAMETER SUMMARY TPARALLEL.
* computes missing data indicator. 

IF (missing(AT_1_Female) OR missing(AT_17_Sunscreen) OR missing(AT_18_Skin_Color)) missing=1.
EXECUTE.


FREQUENCIES VARIABLES=AT_1_Female AT_18_Skin_Color AT_17_Sunscreen
  /STATISTICS=MEAN MEDIAN MODE SKEWNESS SESKEW KURTOSIS SEKURT
  /HISTOGRAM NORMAL
  /ORDER=ANALYSIS.

CROSSTABS
  /TABLES=AT_1_Female BY AT_18_Skin_Color BY AT_17_Sunscreen
  /SHOWDIM=2
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ CORR 
  /CELLS=COUNT EXPECTED ROW COLUMN TOTAL 
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=AT_1_Female BY AT_18_Skin_Color BY AT_17_Sunscreen
  /SHOWDIM=2
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT EXPECTED 
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=AT_1_Female BY AT_18_Skin_Color BY AT_17_Sunscreen
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT EXPECTED 
  /COUNT ROUND CELL.


PLUM AT_17_Sunscreen BY AT_1_Female
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=CELLINFO FIT PARAMETER SUMMARY TPARALLEL.

LOGISTIC REGRESSION VARIABLES Alwas_vs_other
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(3)
  /CONTRAST (AT_1_Female)=Indicator(2)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES Frequently_vs_other
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(3)
  /CONTRAST (AT_1_Female)=Indicator(2)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES sometimes_vs_other
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(3)
  /CONTRAST (AT_1_Female)=Indicator(2)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES rarely_vs_other
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(3)
  /CONTRAST (AT_1_Female)=Indicator(2)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES never_vs_other
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(3)
  /CONTRAST (AT_1_Female)=Indicator(2)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

DATASET ACTIVATE DataSet6.
UNIANOVA AT_17_Sunscreen BY AT_18_Skin_Color
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /SAVE=PRED RESID
  /CRITERIA=ALPHA(0.05)
  /DESIGN=AT_18_Skin_Color.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT AT_17_Sunscreen
  /METHOD=ENTER AT_18_Skin_Color
  /SCATTERPLOT=(*ZRESID ,*ZPRED)
  /RESIDUALS HISTOGRAM(ZRESID) NORMPROB(ZRESID).

GRAPH
  /SCATTERPLOT(BIVAR)=PRE_1 WITH RES_1
  /MISSING=LISTWISE.

DESCRIPTIVES VARIABLES=AT_3_Age
  /STATISTICS=MEAN STDDEV MIN MAX KURTOSIS SKEWNESS.

FREQUENCIES VARIABLES=AT_1_Female
  /NTILES=4
  /STATISTICS=SKEWNESS SESKEW KURTOSIS SEKURT
  /HISTOGRAM NORMAL
  /ORDER=ANALYSIS.

PLUM AT_17_Sunscreen BY AT_1_Female WITH AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female WITH AT_18_Skin_Color AT_3_Age
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female AT_18_Skin_Color WITH AT_3_Age
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.


DATASET ACTIVATE DataSet1.
FREQUENCIES VARIABLES=AT_2_Country_Birth
  /ORDER=ANALYSIS.


RECODE AT_2_Country_Birth ('Argentina'=1) ('Chile'=2) ('Colombia'=3) ('Costa Rica'=4) 
    ('El Salvador'=5) ('Guatemala'=6) ('Honduras'=7) ('Salvador'=5) ('Peru'=9) ('Mexico'=8) 
    ('Puerto Rico'=10) ('Republica Dominicana'=11) ('USA'=12) ('Venezuela'=13) INTO 
    AT_2_Numeric.
VARIABLE LABELS  AT_2_Numeric 'Country of Birth'.
EXECUTE.

PLUM AT_17_Sunscreen BY AT_2_Numeric AT_1_Female AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /LOCATION=AT_2_Numeric AT_1_Female AT_18_Skin_Color AT_18_Skin_Color*AT_1_Female 
    AT_18_Skin_Color*AT_2_Numeric AT_1_Female*AT_2_Numeric AT_18_Skin_Color*AT_1_Female*AT_2_Numeric 
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

DESCRIPTIVES VARIABLES=AT_3_Age
  /STATISTICS=MEAN STDDEV MIN MAX.

RECODE AT_3_Age (Lowest thru 38=1) (39 thru 58=2) (59 thru 78=3) INTO Age_Stratified.
VARIABLE LABELS  Age_Stratified 'Stratified age by 20 year increments'.
EXECUTE.

PLUM AT_17_Sunscreen BY AT_2_Numeric AT_1_Female WITH AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /LOCATION=AT_2_Numeric AT_1_Female AT_1_Female*AT_2_Numeric 
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.



PLUM AT_17_Sunscreen BY AT_1_Female AT_18_Skin_Color Age_Stratified
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /LOCATION=AT_1_Female 
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

FREQUENCIES VARIABLES=AT_3_Age
  /ORDER=ANALYSIS.

COMPUTE Z_Age=MEAN(AT_3_Age)/10.624.
EXECUTE.

DESCRIPTIVES VARIABLES=AT_3_Age
  /SAVE
  /STATISTICS=MEAN STDDEV VARIANCE RANGE MIN MAX KURTOSIS SKEWNESS.

FREQUENCIES VARIABLES=A_5_Years_School_Completed
  /ORDER=ANALYSIS.

PLUM AT_17_Sunscreen BY AT_1_Female AT_18_Skin_Color WITH AT_3_Age
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female AT_18_Skin_Color AT_3_Age
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female AT_18_Skin_Color Age_Stratified WITH A_5_Years_School_Completed
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

RECODE A_5_Years_School_Completed (Lowest thru 5=1) (6 thru 8=2) (9 thru 12=3) (13 thru Highest=4) 
    INTO School_Years_Strata.
VARIABLE LABELS  School_Years_Strata 'Elementry, Middle, High, college'.
EXECUTE.


PLUM AT_17_Sunscreen BY Age_Stratified School_Years_Strata WITH AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female WITH AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female AT_2_Numeric WITH AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female WITH AT_18_Skin_Color
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

IF  (AT_18_Skin_Color=1) Skin_Color_fair=1.
EXECUTE.

IF  (AT_18_Skin_Color=2) Skin_Color_light=1.
EXECUTE.

IF  (AT_18_Skin_Color=3) Skin_Color_dark=1.
EXECUTE.

IF  (AT_17_Sunscreen=1) Sunscreen_Always=1.
EXECUTE.

IF  (AT_17_Sunscreen=2) Sunscreen_Frequently=1.
EXECUTE.

IF  (AT_17_Sunscreen=3) Sunscreen_sometimes=1.
EXECUTE.

IF  (AT_17_Sunscreen=4) Sunscreen_Rarely=1.
EXECUTE.

IF  (AT_17_Sunscreen=5) Sunscreen_Never=1.
EXECUTE.

LOGISTIC REGRESSION VARIABLES Sunscreen_Always
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(1)
  /CONTRAST (AT_1_Female)=Indicator(1)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES Sunscreen_Frequently
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(1)
  /CONTRAST (AT_1_Female)=Indicator(1)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES Sunscreen_sometimes
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(1)
  /CONTRAST (AT_1_Female)=Indicator(1)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES Sunscreen_Rarely
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(1)
  /CONTRAST (AT_1_Female)=Indicator(1)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES Sunscreen_Never
  /METHOD=ENTER AT_18_Skin_Color AT_1_Female 
  /CONTRAST (AT_18_Skin_Color)=Indicator(1)
  /CONTRAST (AT_1_Female)=Indicator(1)
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

PLUM AT_17_Sunscreen BY AT_1_Female AT_2_Numeric WITH A_5_Years_School_Completed
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

PLUM AT_17_Sunscreen BY AT_1_Female WITH A_5_Years_School_Completed
  /CRITERIA=CIN(95) DELTA(0) LCONVERGE(0) MXITER(100) MXSTEP(5) PCONVERGE(1.0E-6) SINGULAR(1.0E-8)
  /LINK=LOGIT
  /PRINT=FIT PARAMETER SUMMARY TPARALLEL.

EXAMINE VARIABLES=A_4_Marital_Status BY AT_2a_Time_US_Months AT_1_Female A_5_Years_School_Completed 
    AT_3_Age A_8_People_Support_Income_US
  /PLOT BOXPLOT HISTOGRAM NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

EXAMINE VARIABLES=A_4_Marital_Status BY AT_1_Female A_5_Years_School_Completed AT_3_Age 
    A_8_People_Support_Income_US
  /PLOT BOXPLOT HISTOGRAM NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

DATASET ACTIVATE DataSet1.
FREQUENCIES VARIABLES=AT_17_Sunscreen
  /NTILES=4
  /STATISTICS=STDDEV MEAN MEDIAN MODE
  /HISTOGRAM NORMAL
  /ORDER=ANALYSIS.



LOGISTIC REGRESSION VARIABLES Sunscreen_Never
  /METHOD=ENTER AT_1_Female AT_18_Skin_Color 
  /METHOD=ENTER AT_3_Age A_5_Years_School_Completed 
  /CONTRAST (AT_1_Female)=Indicator(1)
  /CONTRAST (AT_18_Skin_Color)=Indicator
  /PRINT=CI(95)
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).

LOGISTIC REGRESSION VARIABLES Sunscreen_Never
  /METHOD=ENTER AT_1_Female AT_18_Skin_Color AT_3_Age A_5_Years_School_Completed 
  /CONTRAST (AT_1_Female)=Indicator(1)
  /CONTRAST (AT_18_Skin_Color)=Indicator
  /PRINT=CI(95)
  /CRITERIA=PIN(0.05) POUT(0.10) ITERATE(20) CUT(0.5).

DATASET ACTIVATE DataSet1.
DESCRIPTIVES VARIABLES=AT_1_Female AT_3_Age AT_18_Skin_Color A_5_Years_School_Completed 
    AT_17_Sunscreen Sunscreen_Never
  /STATISTICS=MEAN STDDEV MIN MAX KURTOSIS SKEWNESS.

COMPUTE ln_age=ln(AT_3_Age).
EXECUTE.

COMPUTE ln_school=ln(A_5_Years_School_Completed).
EXECUTE.

FREQUENCIES VARIABLES=AT_1_Female AT_18_Skin_Color AT_17_Sunscreen
  /ORDER=ANALYSIS.

COMPUTE ln_schoolxschool=ln_school * A_5_Years_School_Completed.
EXECUTE.

COMPUTE ln_agexage=ln_age * AT_3_Age.
EXECUTE.

LOGISTIC REGRESSION VARIABLES Sunscreen_Never
  /METHOD=ENTER ln_agexage ln_schoolxschool A_5_Years_School_Completed AT_3_Age 
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

FREQUENCIES VARIABLES=A_5_Years_School_Completed
  /HISTOGRAM NORMAL
  /ORDER=ANALYSIS.

LOGISTIC REGRESSION VARIABLES Sunscreen_Never
  /METHOD=ENTER ln_agexage AT_3_Age ln_age 
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

LOGISTIC REGRESSION VARIABLES Sunscreen_Never
  /METHOD=ENTER ln_schoolxschool A_5_Years_School_Completed ln_school 
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL ZPP
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Sunscreen_Never
  /METHOD=ENTER AT_3_Age A_5_Years_School_Completed AT_1_Female AT_18_Skin_Color
  /SCATTERPLOT=(*ZRESID ,*ZPRED)
  /RESIDUALS HISTOGRAM(ZRESID) NORMPROB(ZRESID).


CROSSTABS
  /TABLES=AT_1_Female BY AT_18_Skin_Color BY Sunscreen_Never
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ CORR 
  /CELLS=COUNT EXPECTED 
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=AT_1_Female BY AT_18_Skin_Color BY Sunscreen_Never
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ CORR 
  /CELLS=COUNT 
  /COUNT ROUND CELL.
