* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
T-TEST PAIRS=ACC dmPFC IFG IPL PHG SFG WITH ACC_NoC dmPFC_NoC IFG_NoC IPL_NoC PHG_NoC SFG_NoC 
    (PAIRED)
  /ES DISPLAY(TRUE) STANDARDIZER(SD)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.

T-TEST GROUPS=PAIN(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=ACC dmPFC IFG IPL PHG SFG
  /ES DISPLAY(TRUE)
  /CRITERIA=CI(.95).

T-TEST GROUPS=PAIN(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=ACC_NoC dmPFC_NoC IFG_NoC IPL_NoC PHG_NoC SFG_NoC
  /ES DISPLAY(TRUE)
  /CRITERIA=CI(.95).
